//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINAprojektet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LINAsDatabasEntities : DbContext
    {
        public LINAsDatabasEntities()
            : base("name=LINAsDatabasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Medfinansiar> Medfinansiar { get; set; }
        public DbSet<MedfinansiarProjekt> MedfinansiarProjekt { get; set; }
        public DbSet<MedverkandeFranHV> MedverkandeFranHV { get; set; }
        public DbSet<Nyckelord> Nyckelord { get; set; }
        public DbSet<Projekt> Projekt { get; set; }
    }
}
