//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINAprojektet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LINAsDatabasEntities1 : DbContext
    {
        public LINAsDatabasEntities1()
            : base("name=LINAsDatabasEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Medfinansiar> Medfinansiar { get; set; }
        public virtual DbSet<MedfinansiarProjekt> MedfinansiarProjekt { get; set; }
        public virtual DbSet<MedverkandeFranHV> MedverkandeFranHV { get; set; }
        public virtual DbSet<Nyckelord> Nyckelord { get; set; }
        public virtual DbSet<Projekt> Projekt { get; set; }
    }
}
