//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINAprojektet
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Projekt
    {
        public Projekt()
        {
            this.MedfinansiarProjekt = new HashSet<MedfinansiarProjekt>();
            this.MedverkandeFranHV = new HashSet<MedverkandeFranHV>();
            this.Nyckelord = new HashSet<Nyckelord>();
        }
    
        public int ID { get; set; }
        public string Projektnamn { get; set; }
        public string Beskrivning { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Starttid { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Sluttid { get; set; }
        public string Huvudansvarig { get; set; }
        public string Diarienummer { get; set; }
        public decimal SoktBelopp { get; set; }
        public string Huvudfinansiar { get; set; }
        public string Projekttyp { get; set; }
        public int Projektstatus { get; set; }
        public bool Beviljat { get; set; }
        public bool HVSomHuvudansvarig { get; set; }
        public int Kommuniceringsstatus { get; set; }
        public string TillagdAv { get; set; }

        public virtual ICollection<MedfinansiarProjekt> MedfinansiarProjekt { get; set; }
        public virtual ICollection<MedverkandeFranHV> MedverkandeFranHV { get; set; }
        public virtual ICollection<Nyckelord> Nyckelord { get; set; }
    }
}
